{
 "title": "risingwave_user_dashboard",
 "description": "RisingWave User Dashboard",
 "tags": [ "risingwave" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregated Source Throughput(rows/s)",
   "type": "timeseries",
   "description": "The figure shows the number of rows read by each source per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "sum(rate(stream_source_output_rows_counts[$__rate_interval])) by (source_name)",
     "legendFormat": "{{source_name}}",
     "query": "sum(rate(stream_source_output_rows_counts[$__rate_interval])) by (source_name)"
    }
   ]
  },
  {
   "title": "Aggregated Source Throughput(MB/s)",
   "type": "timeseries",
   "description": "The figure shows the number of bytes read by each source per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "expr": "(sum by (source_id)(rate(partition_input_bytes[$__rate_interval])))/(1000*1000)",
     "legendFormat": "source_id {{source_id}}",
     "query": "(sum by (source_id)(rate(partition_input_bytes[$__rate_interval])))/(1000*1000)"
    }
   ]
  },
  {
   "title": "Barrier Latency",
   "type": "timeseries",
   "description": "The time that the data between two consecutive barriers gets fully processed, i.e. the computation results are made durable into materialized views or sink to external systems. This metric shows to users the freshness of materialized views.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p50",
     "query": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p99",
     "query": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum[$__rate_interval]) / rate(meta_barrier_duration_seconds_count[$__rate_interval])",
     "legendFormat": "barrier_latency_avg",
     "query": "rate(meta_barrier_duration_seconds_sum[$__rate_interval]) / rate(meta_barrier_duration_seconds_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Errors by Type",
   "type": "timeseries",
   "description": "Errors in the system group by type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(user_compute_error_count) by (error_type, error_msg, fragment_id, executor_name)",
     "legendFormat": "compute error {{error_type}}: {{error_msg}} ({{executor_name}}: fragment_id={{fragment_id}})",
     "query": "sum(user_compute_error_count) by (error_type, error_msg, fragment_id, executor_name)"
    },
    {
     "expr": "sum(user_source_error_count) by (error_type, error_msg, fragment_id, table_id, executor_name)",
     "legendFormat": "source error {{error_type}}: {{error_msg}} ({{executor_name}}: table_id={{table_id}}, fragment_id={{fragment_id}})",
     "query": "sum(user_source_error_count) by (error_type, error_msg, fragment_id, table_id, executor_name)"
    },
    {
     "expr": "sum(rate(object_store_failure_count[$__rate_interval])) by (instance, job, type)",
     "legendFormat": "remote storage error {{type}}: {{job}} @ {{instance}}",
     "query": "sum(rate(object_store_failure_count[$__rate_interval])) by (instance, job, type)"
    }
   ]
  },
  {
   "title": "Batch Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Qps" } },
   "targets": [
    {
     "expr": "rate(frontend_query_counter_local_execution[$__rate_interval])",
     "legendFormat": "Local mode",
     "query": "rate(frontend_query_counter_local_execution[$__rate_interval])"
    },
    {
     "expr": "rate(distributed_completed_query_counter[$__rate_interval])",
     "legendFormat": "Distributed mode",
     "query": "rate(distributed_completed_query_counter[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "description": "The number of each type of RisingWave components alive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(worker_num) by (worker_type)",
     "legendFormat": "{{worker_type}}",
     "query": "sum(worker_num) by (worker_type)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "description": "The CPU usage of each RisingWave component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}",
       "query": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (instance)"
      }
     ]
    },
    {
     "title": "Node CPU Core Number",
     "type": "timeseries",
     "description": "Number of CPU cores per RisingWave component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(process_cpu_core_num) by (instance)",
       "legendFormat": "{{instance}}",
       "query": "avg(process_cpu_core_num) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory",
     "type": "timeseries",
     "description": "The memory usage of each RisingWave component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes) by (job,instance)",
       "legendFormat": "{{job}} @ {{instance}}",
       "query": "avg(process_resident_memory_bytes) by (job,instance)"
      }
     ]
    },
    {
     "title": "Memory Usage (Total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(stream_total_mem_usage) by (instance)",
       "legendFormat": "streaming @ {{instance}}",
       "query": "sum(stream_total_mem_usage) by (instance)"
      },
      {
       "expr": "sum(batch_total_mem_usage) by (instance)",
       "legendFormat": "batch @ {{instance}}",
       "query": "sum(batch_total_mem_usage) by (instance)"
      },
      {
       "expr": "sum(state_store_meta_cache_size) by (instance) + sum(state_store_block_cache_size) by (instance) + sum(state_store_limit_memory_size) by (instance)",
       "legendFormat": "storage @ {{instance}}",
       "query": "sum(state_store_meta_cache_size) by (instance) + sum(state_store_block_cache_size) by (instance) + sum(state_store_limit_memory_size) by (instance)"
      }
     ]
    },
    {
     "title": "Memory Usage (Detailed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(actor_memory_usage[$__rate_interval])",
       "legendFormat": "streaming actor - {{actor_id}}",
       "query": "rate(actor_memory_usage[$__rate_interval])"
      },
      {
       "expr": "sum(state_store_meta_cache_size) by (job,instance)",
       "legendFormat": "storage meta cache - {{job}} @ {{instance}}",
       "query": "sum(state_store_meta_cache_size) by (job,instance)"
      },
      {
       "expr": "sum(state_store_block_cache_size) by (job,instance)",
       "legendFormat": "storage block cache - {{job}} @ {{instance}}",
       "query": "sum(state_store_block_cache_size) by (job,instance)"
      },
      {
       "expr": "sum(state_store_limit_memory_size) by (job,instance)",
       "legendFormat": "storage write buffer - {{job}} @ {{instance}}",
       "query": "sum(state_store_limit_memory_size) by (job,instance)"
      }
     ]
    },
    {
     "title": "Executor Cache",
     "type": "timeseries",
     "description": "Executor cache statistics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_join_lookup_miss_count[$__rate_interval])",
       "legendFormat": "Join - cache miss {{actor_id}} {{side}}",
       "query": "rate(stream_join_lookup_miss_count[$__rate_interval])"
      },
      {
       "expr": "rate(stream_join_lookup_total_count[$__rate_interval])",
       "legendFormat": "Join - total lookups {{actor_id}} {{side}}",
       "query": "rate(stream_join_lookup_total_count[$__rate_interval])"
      },
      {
       "expr": "rate(stream_agg_lookup_miss_count[$__rate_interval])",
       "legendFormat": "Agg - cache miss {{actor_id}}",
       "query": "rate(stream_agg_lookup_miss_count[$__rate_interval])"
      },
      {
       "expr": "rate(stream_agg_lookup_total_count[$__rate_interval])",
       "legendFormat": "Agg - total lookups {{actor_id}}",
       "query": "rate(stream_agg_lookup_total_count[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Storage Cache",
     "type": "timeseries",
     "description": "Storage cache statistics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(state_store_sst_store_block_request_counts[$__rate_interval])) by (job, instance, table_id, type)",
       "legendFormat": "memory cache - {{table_id}} @ {{type}} @ {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_sst_store_block_request_counts[$__rate_interval])) by (job, instance, table_id, type)"
      },
      {
       "expr": "sum(rate(state_store_read_req_check_bloom_filter_counts[$__rate_interval])) by (job,instance,table_id)",
       "legendFormat": "bloom filter total - {{table_id}} @ {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_read_req_check_bloom_filter_counts[$__rate_interval])) by (job,instance,table_id)"
      },
      {
       "expr": "sum(rate(state_store_read_req_positive_but_non_exist_counts[$__rate_interval])) by (job,instance,table_id)",
       "legendFormat": "bloom filter false positive  - {{table_id}} @ {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_read_req_positive_but_non_exist_counts[$__rate_interval])) by (job,instance,table_id)"
      },
      {
       "expr": "sum(rate(file_cache_latency_count[$__rate_interval])) by (op, instance)",
       "legendFormat": "file cache {{op}} @ {{instance}}",
       "query": "sum(rate(file_cache_latency_count[$__rate_interval])) by (op, instance)"
      },
      {
       "expr": "sum(rate(file_cache_miss[$__rate_interval])) by (instance)",
       "legendFormat": "file cache miss @ {{instance}}",
       "query": "sum(rate(file_cache_miss[$__rate_interval])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Streming Remote Exchange (Bytes/s)",
     "type": "timeseries",
     "description": "Send/Recv throughput per node for streaming exchange",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(stream_exchange_frag_send_size[$__rate_interval])) by (instance)",
       "legendFormat": "Send @ {{instance}}",
       "query": "sum(rate(stream_exchange_frag_send_size[$__rate_interval])) by (instance)"
      },
      {
       "expr": "sum(rate(stream_exchange_frag_recv_size[$__rate_interval])) by (instance)",
       "legendFormat": "Recv @ {{instance}}",
       "query": "sum(rate(stream_exchange_frag_recv_size[$__rate_interval])) by (instance)"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (Bytes/s)",
     "type": "timeseries",
     "description": "The remote storage read/write throughput per node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes[$__rate_interval])) by (instance)",
       "legendFormat": "read - {{instance}}",
       "query": "sum(rate(object_store_read_bytes[$__rate_interval])) by (instance)"
      },
      {
       "expr": "sum(rate(object_store_write_bytes[$__rate_interval])) by (instance)",
       "legendFormat": "write - {{instance}}",
       "query": "sum(rate(object_store_write_bytes[$__rate_interval])) by (instance)"
      }
     ]
    },
    {
     "title": "Batch Exchange Recv (Rows/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "batch_task_exchange_recv_row_number",
       "legendFormat": "{{query_id}} : {{source_stage_id}}.{{source_task_id}} -> {{target_stage_id}}.{{target_task_id}}",
       "query": "batch_task_exchange_recv_row_number"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Size (KB)",
     "type": "timeseries",
     "description": "KBs total file bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_total_file_size)",
       "legendFormat": "Current Version",
       "query": "sum(storage_level_total_file_size)"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "timeseries",
     "description": "The number of bytes that have been written by compaction.Flush refers to the process of compacting Memtables to SSTables at Level 0.Compaction refers to the process of compacting SSTables at one level to another level.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_compact_write) by (job) > 0",
       "legendFormat": "Compaction - {{job}}",
       "query": "sum(storage_level_compact_write) by (job) > 0"
      },
      {
       "expr": "sum(compactor_write_build_l0_bytes) by (job) > 0",
       "legendFormat": "Flush - {{job}}",
       "query": "sum(compactor_write_build_l0_bytes) by (job) > 0"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (Bytes/s)",
     "type": "timeseries",
     "description": "The remote storage read/write throughput",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes[$__rate_interval])) by (job)",
       "legendFormat": "read - {{job}}",
       "query": "sum(rate(object_store_read_bytes[$__rate_interval])) by (job)"
      },
      {
       "expr": "sum(rate(object_store_write_bytes[$__rate_interval])) by (job)",
       "legendFormat": "write - {{job}}",
       "query": "sum(rate(object_store_write_bytes[$__rate_interval])) by (job)"
      }
     ]
    },
    {
     "title": "Checkpoint Size",
     "type": "timeseries",
     "description": "Size statistics for checkpoint",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_sync_size_bucket[$__rate_interval])) by (le, job))",
       "legendFormat": "p50 - {{job}}",
       "query": "histogram_quantile(0.5, sum(rate(state_store_sync_size_bucket[$__rate_interval])) by (le, job))"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_sync_size_bucket[$__rate_interval])) by (le, job))",
       "legendFormat": "p99 - {{job}}",
       "query": "histogram_quantile(0.99, sum(rate(state_store_sync_size_bucket[$__rate_interval])) by (le, job))"
      },
      {
       "expr": "sum by(le, job) (rate(state_store_sync_size_sum[$__rate_interval])) / sum by(le, job) (rate(state_store_sync_size_count[$__rate_interval]))",
       "legendFormat": "avg - {{job}}",
       "query": "sum by(le, job) (rate(state_store_sync_size_sum[$__rate_interval])) / sum by(le, job) (rate(state_store_sync_size_count[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source Throughput(rows/s)",
     "type": "timeseries",
     "description": "The figure shows the number of rows read by each source per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_source_output_rows_counts[$__rate_interval])",
       "legendFormat": "source={{source_name}} {{source_id}} @ {{instance}}",
       "query": "rate(stream_source_output_rows_counts[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Source Throughput(MB/s)",
     "type": "timeseries",
     "description": "The figure shows the number of bytes read by each source per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MB/s" } },
     "targets": [
      {
       "expr": "(sum by (source_id)(rate(partition_input_bytes[$__rate_interval])))/(1000*1000)",
       "legendFormat": "source={{source_id}}",
       "query": "(sum by (source_id)(rate(partition_input_bytes[$__rate_interval])))/(1000*1000)"
      }
     ]
    },
    {
     "title": "Backfill Throughput(rows)",
     "type": "timeseries",
     "description": "Total number of rows that have been read from the backfill operator used by MV on MV",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_backfill_snapshot_read_row_count[$__rate_interval])",
       "legendFormat": "Read Snapshot - table_id={{table_id}} actor={{actor_id}} @ {{instance}}",
       "query": "rate(stream_backfill_snapshot_read_row_count[$__rate_interval])"
      },
      {
       "expr": "rate(stream_backfill_upstream_output_row_count[$__rate_interval])",
       "legendFormat": "Upstream - table_id={{table_id}} actor={{actor_id}} @ {{instance}}",
       "query": "rate(stream_backfill_upstream_output_row_count[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Actor Backpressure",
     "type": "timeseries",
     "description": "We first record the total blocking duration(ns) of output buffer of each actor. It shows how much time it takes an actor to process a message, i.e. a barrier, a watermark or rows of data, on average. Then we divide this duration by 1 second and show it as a percentage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_actor_output_buffer_blocking_duration_ns[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}",
       "query": "rate(stream_actor_output_buffer_blocking_duration_ns[$__rate_interval]) / 1000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "distributed_running_query_num",
       "legendFormat": "The number of running query in distributed execution mode",
       "query": "distributed_running_query_num"
      }
     ]
    },
    {
     "title": "Rejected query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "distributed_rejected_query_counter",
       "legendFormat": "The number of rejected query in distributed execution mode",
       "query": "distributed_rejected_query_counter"
      }
     ]
    },
    {
     "title": "Completed query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "distributed_completed_query_counter",
       "legendFormat": "The number of completed query in distributed execution mode",
       "query": "distributed_completed_query_counter"
      }
     ]
    },
    {
     "title": "Query Latency in Distributed Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p50 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.5, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p90 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.9, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p99 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.95, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))"
      }
     ]
    },
    {
     "title": "Query Latency in Local Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p50 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.5, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p90 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.9, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p99 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.95, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))"
      }
     ]
    }
   ]
  }
 ]
}