{
 "title": "risingwave_dashboard",
 "description": "RisingWave Dashboard",
 "tags": [ "risingwave" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Actor/Table Id Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Actor Id Info",
   "type": "table",
   "description": "Mapping from actor id to fragment id",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "actor_info" }
   ]
  },
  {
   "title": "Table Id Info",
   "type": "table",
   "description": "Mapping from table id to actor id and table name",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "table_info" }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Aggregated Source Throughput(rows/s)",
   "type": "timeseries",
   "description": "The figure shows the number of rows read by each source per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "sum(rate(stream_source_output_rows_counts[$__rate_interval])) by (source_name)",
     "legendFormat": "{{source_name}}"
    }
   ]
  },
  {
   "title": "Aggregated Source Throughput(MB/s)",
   "type": "timeseries",
   "description": "The figure shows the number of bytes read by each source per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "expr": "(sum by (source_id)(rate(partition_input_bytes[$__rate_interval])))/(1000*1000)",
     "legendFormat": "source_id {{source_id}}"
    }
   ]
  },
  {
   "title": "Aggregated Sink Throughput(rows/s)",
   "type": "timeseries",
   "description": "The figure shows the number of rows output by each sink per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "sum(rate(stream_sink_output_rows_counts[$__rate_interval])) by (source_name)",
     "legendFormat": "{{source_name}}"
    }
   ]
  },
  {
   "title": "Barrier Latency",
   "type": "timeseries",
   "description": "The time that the data between two consecutive barriers gets fully processed, i.e. the computation results are made durable into materialized views or sink to external systems. This metric shows to users the freshness of materialized views.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p99"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum[$__rate_interval]) / rate(meta_barrier_duration_seconds_count[$__rate_interval])",
     "legendFormat": "barrier_latency_avg"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "timeseries",
   "description": "Alerts in the system group by type:\n            - Too Many Barriers: there are too many uncommitted barriers generated. This means the streaming graph is stuck or under heavy load. Check 'Barrier Latency' panel.\n            - Recovery Triggered: cluster recovery is triggered. Check 'Errors by Type' / 'Node Count' panels.\n            - Lagging Version: the checkpointed or pinned version id is lagging behind the current version id. Check 'Hummock Manager' section in dev dashboard.\n            - Lagging Epoch: the pinned or safe epoch is lagging behind the current max committed epoch. Check 'Hummock Manager' section in dev dashboard.\n            - Lagging Compaction: there are too many files in L0. This can be caused by compactor failure or lag of compactor resource. Check 'Compaction' section in dev dashboard.\n            - Lagging Vacuum: there are too many stale files waiting to be cleaned. This can be caused by compactor failure or lag of compactor resource. Check 'Compaction' section in dev dashboard.\n            ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "all_barrier_nums >= bool 200", "legendFormat": "Too Many Barriers" },
    {
     "expr": "sum(rate(recovery_latency_count[$__rate_interval])) > bool 0 + sum(recovery_failure_cnt) > bool 0",
     "legendFormat": "Recovery Triggered"
    },
    {
     "expr": "((storage_current_version_id - storage_checkpoint_version_id) >= bool 100) + ((storage_current_version_id - storage_min_pinned_version_id) >= bool 100)",
     "legendFormat": "Lagging Version"
    },
    {
     "expr": "((storage_max_committed_epoch - storage_min_pinned_epoch) >= bool 6553600000 unless + storage_min_pinned_epoch == 0) + ((storage_max_committed_epoch - storage_safe_epoch) >= bool 6553600000 unless + storage_safe_epoch == 0)",
     "legendFormat": "Lagging Epoch"
    },
    {
     "expr": "sum(label_replace(storage_level_sst_num, 'L0', 'L0', 'level_index', '.*_L0') unless storage_level_sst_num) by (L0) >= bool 200",
     "legendFormat": "Lagging Compaction"
    },
    {
     "expr": "storage_stale_object_count >= bool 200",
     "legendFormat": "Lagging Vacuum"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors in the system group by type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(user_compute_error_count) by (error_type, error_msg, fragment_id, executor_name)",
     "legendFormat": "compute error {{error_type}}: {{error_msg}} ({{executor_name}}: fragment_id={{fragment_id}})"
    },
    {
     "expr": "sum(user_source_error_count) by (error_type, error_msg, fragment_id, table_id, executor_name)",
     "legendFormat": "parse error {{error_type}}: {{error_msg}} ({{executor_name}}: table_id={{table_id}}, fragment_id={{fragment_id}})"
    },
    {
     "expr": "source_status_is_up == 0",
     "legendFormat": "source error: source_id={{source_id}}, source_name={{source_name}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(object_store_failure_count[$__rate_interval])) by (instance, job, type)",
     "legendFormat": "remote storage error {{type}}: {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Batch Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Qps" } },
   "targets": [
    {
     "expr": "rate(frontend_query_counter_local_execution[$__rate_interval])",
     "legendFormat": "Local mode"
    },
    {
     "expr": "rate(distributed_completed_query_counter[$__rate_interval])",
     "legendFormat": "Distributed mode"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "description": "The number of each type of RisingWave components alive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(worker_num) by (worker_type)",
     "legendFormat": "{{worker_type}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "description": "The CPU usage of each RisingWave component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node CPU Core Number",
     "type": "timeseries",
     "description": "Number of CPU cores per RisingWave component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "avg(process_cpu_core_num) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory",
     "type": "timeseries",
     "description": "The memory usage of each RisingWave component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes) by (job,instance)",
       "legendFormat": "{{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage (Total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(state_store_meta_cache_size) by (instance) + sum(state_store_block_cache_size) by (instance) + sum(state_store_limit_memory_size) by (instance)",
       "legendFormat": "storage @ {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage (Detailed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(actor_memory_usage[$__rate_interval])",
       "legendFormat": "streaming actor - {{actor_id}}"
      },
      {
       "expr": "sum(state_store_meta_cache_size) by (job,instance)",
       "legendFormat": "storage meta cache - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(state_store_block_cache_size) by (job,instance)",
       "legendFormat": "storage block cache - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(state_store_limit_memory_size) by (job,instance)",
       "legendFormat": "storage write buffer - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Executor Cache",
     "type": "timeseries",
     "description": "Executor cache statistics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_join_lookup_miss_count[$__rate_interval])",
       "legendFormat": "Join - cache miss - {{side}} side, join_table_id {{join_table_id}} degree_table_id {{degree_table_id}} actor {{actor_id}}"
      },
      {
       "expr": "rate(stream_join_lookup_total_count[$__rate_interval])",
       "legendFormat": "Join - total lookups - {{side}} side, join_table_id {{join_table_id}} degree_table_id {{degree_table_id}} actor {{actor_id}}"
      },
      {
       "expr": "rate(stream_agg_lookup_miss_count[$__rate_interval])",
       "legendFormat": "Agg - cache miss - table {{table_id}} actor {{actor_id}}"
      },
      {
       "expr": "rate(stream_agg_distinct_cache_miss_count[$__rate_interval])",
       "legendFormat": "Distinct agg cache miss - table {{table_id}} actor {{actor_id}}"
      },
      {
       "expr": "rate(stream_agg_lookup_total_count[$__rate_interval])",
       "legendFormat": "Agg - total lookups - table {{table_id}} actor {{actor_id}}"
      },
      {
       "expr": "rate(stream_materialize_cache_hit_count[$__rate_interval])",
       "legendFormat": "Materialize - cache hit count - table {{table_id}} - actor {{actor_id}}  {{instance}}"
      },
      {
       "expr": "rate(stream_materialize_cache_total_count[$__rate_interval])",
       "legendFormat": "Materialize - total cache count - table {{table_id}} - actor {{actor_id}}  {{instance}}"
      }
     ]
    },
    {
     "title": "Executor Cache Miss Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(stream_join_lookup_miss_count[$__rate_interval])) by (side, join_table_id, degree_table_id, actor_id) ) / (sum(rate(stream_join_lookup_total_count[$__rate_interval])) by (side, join_table_id, degree_table_id, actor_id))",
       "legendFormat": "join executor cache miss ratio - - {{side}} side, join_table_id {{join_table_id}} degree_table_id {{degree_table_id}} actor {{actor_id}}"
      },
      {
       "expr": "(sum(rate(stream_agg_lookup_miss_count[$__rate_interval])) by (table_id, actor_id) ) / (sum(rate(stream_agg_lookup_total_count[$__rate_interval])) by (table_id, actor_id))",
       "legendFormat": "Agg cache miss ratio - table {{table_id}} actor {{actor_id}} "
      },
      {
       "expr": "(sum(rate(stream_agg_distinct_cache_miss_count[$__rate_interval])) by (table_id, actor_id) ) / (sum(rate(stream_agg_distinct_total_cache_count[$__rate_interval])) by (table_id, actor_id))",
       "legendFormat": "Distinct agg cache miss ratio - table {{table_id}} actor {{actor_id}} "
      },
      {
       "expr": "1 - (sum(rate(stream_materialize_cache_hit_count[$__rate_interval])) by (table_id, actor_id) ) / (sum(rate(stream_materialize_cache_total_count[$__rate_interval])) by (table_id, actor_id))",
       "legendFormat": "materialize executor cache miss ratio - table {{table_id}} - actor {{actor_id}}  {{instance}}"
      }
     ]
    },
    {
     "title": "Storage Cache",
     "type": "timeseries",
     "description": "Storage cache statistics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(state_store_sst_store_block_request_counts[$__rate_interval])) by (job, instance, table_id, type)",
       "legendFormat": "memory cache - {{table_id}} @ {{type}} @ {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(state_store_sst_store_block_request_counts{type='meta_miss'}[$__rate_interval])) by (job, type)",
       "legendFormat": "total_meta_miss_count - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Storage Bloom Filer",
     "type": "timeseries",
     "description": "Storage bloom filter statistics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(state_store_read_req_check_bloom_filter_counts[$__rate_interval])) by (job,instance,table_id)",
       "legendFormat": "bloom filter total - {{table_id}} @ {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(state_store_read_req_positive_but_non_exist_counts[$__rate_interval])) by (job,instance,table_id)",
       "legendFormat": "bloom filter false positive  - {{table_id}} @ {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Storage File Cache",
     "type": "timeseries",
     "description": "Storage file cache statistics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(file_cache_latency_count[$__rate_interval])) by (op, instance)",
       "legendFormat": "file cache {{op}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_miss[$__rate_interval])) by (instance)",
       "legendFormat": "file cache miss @ {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Streming Remote Exchange (Bytes/s)",
     "type": "timeseries",
     "description": "Send/Recv throughput per node for streaming exchange",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(stream_exchange_frag_send_size[$__rate_interval])) by (instance)",
       "legendFormat": "Send @ {{instance}}"
      },
      {
       "expr": "sum(rate(stream_exchange_frag_recv_size[$__rate_interval])) by (instance)",
       "legendFormat": "Recv @ {{instance}}"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (Bytes/s)",
     "type": "timeseries",
     "description": "The remote storage read/write throughput per node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes[$__rate_interval])) by (instance)",
       "legendFormat": "read - {{instance}}"
      },
      {
       "expr": "sum(rate(object_store_write_bytes[$__rate_interval])) by (instance)",
       "legendFormat": "write - {{instance}}"
      }
     ]
    },
    {
     "title": "Batch Exchange Recv (Rows/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "batch_exchange_recv_row_number",
       "legendFormat": "{{query_id}} : {{source_stage_id}}.{{source_task_id}} -> {{target_stage_id}}.{{target_task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object Size",
     "type": "timeseries",
     "description": "\n                    Objects are classified into 3 groups:\n                    - not referenced by versions: these object are being deleted from object store.\n                    - referenced by non-current versions: these objects are stale (not in the latest version), but those old versions may still be in use (e.g. long-running pinning). Thus those objects cannot be deleted at the moment.\n                    - referenced by current version: these objects are in the latest version.\n                    ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "storage_stale_object_size", "legendFormat": "not referenced by versions" },
      {
       "expr": "storage_old_version_object_size",
       "legendFormat": "referenced by non-current versions"
      },
      {
       "expr": "storage_current_version_object_size",
       "legendFormat": "referenced by current version"
      }
     ]
    },
    {
     "title": "Object Total Number",
     "type": "timeseries",
     "description": "\n                    Objects are classified into 3 groups:\n                    - not referenced by versions: these object are being deleted from object store.\n                    - referenced by non-current versions: these objects are stale (not in the latest version), but those old versions may still be in use (e.g. long-running pinning). Thus those objects cannot be deleted at the moment.\n                    - referenced by current version: these objects are in the latest version.\n                    ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      { "expr": "storage_stale_object_count", "legendFormat": "not referenced by versions" },
      {
       "expr": "storage_old_version_object_count",
       "legendFormat": "referenced by non-current versions"
      },
      {
       "expr": "storage_current_version_object_count",
       "legendFormat": "referenced by current version"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "timeseries",
     "description": "The number of bytes that have been written by compaction.Flush refers to the process of compacting Memtables to SSTables at Level 0.Compaction refers to the process of compacting SSTables at one level to another level.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_compact_write) by (job) > 0",
       "legendFormat": "Compaction - {{job}}"
      },
      {
       "expr": "sum(compactor_write_build_l0_bytes) by (job) > 0",
       "legendFormat": "Flush - {{job}}"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (Bytes/s)",
     "type": "timeseries",
     "description": "The remote storage read/write throughput",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes[$__rate_interval])) by (job)",
       "legendFormat": "read - {{job}}"
      },
      {
       "expr": "sum(rate(object_store_write_bytes[$__rate_interval])) by (job)",
       "legendFormat": "write - {{job}}"
      }
     ]
    },
    {
     "title": "Checkpoint Size",
     "type": "timeseries",
     "description": "Size statistics for checkpoint",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_sync_size_bucket[$__rate_interval])) by (le, job))",
       "legendFormat": "p50 - {{job}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_sync_size_bucket[$__rate_interval])) by (le, job))",
       "legendFormat": "p99 - {{job}}"
      },
      {
       "expr": "sum by(le, job) (rate(state_store_sync_size_sum[$__rate_interval])) / sum by(le, job) (rate(state_store_sync_size_count[$__rate_interval]))",
       "legendFormat": "avg - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source Throughput(rows/s)",
     "type": "timeseries",
     "description": "The figure shows the number of rows read by each source per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_source_output_rows_counts[$__rate_interval])",
       "legendFormat": "source={{source_name}} {{source_id}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Source Throughput(MB/s)",
     "type": "timeseries",
     "description": "The figure shows the number of bytes read by each source per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MB/s" } },
     "targets": [
      {
       "expr": "(sum by (source_id)(rate(partition_input_bytes[$__rate_interval])))/(1000*1000)",
       "legendFormat": "source={{source_id}}"
      }
     ]
    },
    {
     "title": "Backfill Throughput(rows)",
     "type": "timeseries",
     "description": "Total number of rows that have been read from the backfill operator used by MV on MV",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_backfill_snapshot_read_row_count[$__rate_interval])",
       "legendFormat": "Read Snapshot - table_id={{table_id}} actor={{actor_id}} @ {{instance}}"
      },
      {
       "expr": "rate(stream_backfill_upstream_output_row_count[$__rate_interval])",
       "legendFormat": "Upstream - table_id={{table_id}} actor={{actor_id}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Actor Backpressure",
     "type": "timeseries",
     "description": "We first record the total blocking duration(ns) of output buffer of each actor. It shows how much time it takes an actor to process a message, i.e. a barrier, a watermark or rows of data, on average. Then we divide this duration by 1 second and show it as a percentage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_actor_output_buffer_blocking_duration_ns[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "distributed_running_query_num",
       "legendFormat": "The number of running query in distributed execution mode"
      }
     ]
    },
    {
     "title": "Rejected query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "distributed_rejected_query_counter",
       "legendFormat": "The number of rejected query in distributed execution mode"
      }
     ]
    },
    {
     "title": "Completed query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "distributed_completed_query_counter",
       "legendFormat": "The number of completed query in distributed execution mode"
      }
     ]
    },
    {
     "title": "Query Latency in Distributed Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p50 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p90 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(distributed_query_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p99 - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Query Latency in Local Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p50 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p90 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(frontend_latency_local_execution_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p99 - {{job}} @ {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}